[avito]
tg_token = "f9LHodD0cOL9057PbssOV7juUe97DXPd8JvfK3xvPEDeFb0sMwHXq93Q3W0NzJV84fIv3iAOtrNgeP1ZXu48"
tg_chat_id = [8565350, 109794880]
vk_token = ""
vk_user_id = []
urls = [
    "https://www.avito.ru/sankt-peterburg/business360/oborudovanie_dlya_biznesa/promyshlennoe/nasosy_i_kompressory-ASgBAgICAkTqAv5PlpkT3u~NAw?cd=1&f=ASgBAgECA0TqAv5PlpkT3u~NA7CzFP6hjwMBRcaaDBl7ImZyb20iOjEwMDAwLCJ0byI6MTIwMDB9&localPriority=0",
]
count = 5
keys_word_white_list = []
keys_word_black_list = []
seller_black_list = []
max_price = 99999999
min_price = 0
geo = ""
proxy_string = ""
proxy_change_url = ""
pause_general = 1000
pause_between_links = 1000
max_age = 0
max_count_of_retry = 5
ignore_reserv = true
ignore_promotion = false
one_time_start = false
one_file_for_link = false
parse_views = false
save_xlsx = true
use_webdriver = false
use_bypass_api = false
cookies_api_key = ""
use_own_cookies = false
parse_phone = false
proxy_notifier = ""
tg_only_text = false
retry_delay = 5
timeout = 20
block_threshold = 3
