[avito]
tg_token = "f9LHodD0cOL9057PbssOV7juUe97DXPd8JvfK3xvPEDeFb0sMwHXq93Q3W0NzJV84fIv3iAOtrNgeP1ZXu48"
tg_chat_id = [8565350, 109794880]
vk_token = ""
vk_user_id = []
urls = [
    "https://www.avito.ru/sankt-peterburg/oborudovanie_dlya_biznesa/promyshlennoe-ASgBAgICAUTqAv5P?cd=1&f=ASgBAgECAUTqAv5PAUXGmgwdeyJmcm9tIjoxMDAwMDAwLCJ0byI6MjAwMDAwMH0&localPriority=1&q=%D0%B2%D0%B0%D0%BA%D1%83%D1%83%D0%BC%D0%BD%D1%8B%D0%B9+%D0%BD%D0%B0%D1%81%D0%BE%D1%81&s=104",
]
count = 5
keys_word_white_list = []
keys_word_black_list = []
seller_black_list = []
max_price = 99999999
min_price = 0
geo = ""
proxy_string = ""
proxy_change_url = ""
pause_general = 1000
pause_between_links = 1000
max_age = 0
max_count_of_retry = 5
ignore_reserv = true
ignore_promotion = false
one_time_start = false
one_file_for_link = false
parse_views = false
save_xlsx = true
use_webdriver = false
use_bypass_api = false
cookies_api_key = ""
use_own_cookies = false
parse_phone = false
proxy_notifier = ""
tg_only_text = false
retry_delay = 5
timeout = 20
block_threshold = 3
